jobs:
  lint:
    commands:
      - flake8
      - pydocstyle
      - mypy .

  format:
    commands:
      - isort --apply -sl
      - >-
        autoflake . -ri --exclude "venv, conftest.py"
        --remove-all-unused-imports --remove-unused-variables
        --ignore-init-module-imports
      - isort --apply
      - black .

  docs:
    command: sphinx-build docs/ build/

  tests:
    command: pytest --cov yummy_cereal --html .test_report.html --self-contained-html

  release:
    commands:
      - bump2version <release_type>
      - python setup.py sdist bdist_wheel
      - twine upload dist/* --username <twine_username>
    context:
      release_type: patch
      twine_username: joellefkowitz

routines:
  pre-commit:
    - lint
    - comprehensiveTest
    - clean
    - format

meta:
  script_root: ../
  project_root: ../../
